package com.example.myapplication.ui.theme

import androidx.compose.ui.graphics.Color

// Terracotta / peach Material You palette (warm tones)
val md_theme_light_primary = Color(0xFFA55128)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBC8)
val md_theme_light_onPrimaryContainer = Color(0xFF3B1200)
val md_theme_light_secondary = Color(0xFF825940)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBC5)
val md_theme_light_onSecondaryContainer = Color(0xFF2D1600)
val md_theme_light_tertiary = Color(0xFF705D30)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF3D8A9)
val md_theme_light_onTertiaryContainer = Color(0xFF241A00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAF2EE)
val md_theme_light_onBackground = Color(0xFF1A1413)
val md_theme_light_surface = Color(0xFFFAF2EE)
val md_theme_light_onSurface = Color(0xFF1A1413)
val md_theme_light_surfaceVariant = Color(0xFFEBDDD9)
val md_theme_light_onSurfaceVariant = Color(0xFF554A46)
val md_theme_light_outline = Color(0xFF7E7471)
val md_theme_light_outlineVariant = Color(0xFFC4B8B4)
val md_theme_light_inverseSurface = Color(0xFF2C2523)
val md_theme_light_inverseOnSurface = Color(0xFFF3E7E2)
val md_theme_light_inversePrimary = Color(0xFFFFB995)
val md_theme_light_surfaceContainer = Color(0xFFF3E7E2)
val md_theme_light_surfaceContainerHigh = Color(0xFFEBDDD9)
val md_theme_light_surfaceContainerHighest = Color(0xFFDDD1CD)

val md_theme_dark_primary = Color(0xFFFFB995)
val md_theme_dark_onPrimary = Color(0xFF5C2600)
val md_theme_dark_primaryContainer = Color(0xFF803A10)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBC8)
val md_theme_dark_secondary = Color(0xFFFFB994)
val md_theme_dark_onSecondary = Color(0xFF4A2B15)
val md_theme_dark_secondaryContainer = Color(0xFF654127)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBC5)
val md_theme_dark_tertiary = Color(0xFFD4B98A)
val md_theme_dark_onTertiary = Color(0xFF3D2E08)
val md_theme_dark_tertiaryContainer = Color(0xFF55451C)
val md_theme_dark_onTertiaryContainer = Color(0xFFF3D8A9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1413)
val md_theme_dark_onBackground = Color(0xFFF3E7E2)
val md_theme_dark_surface = Color(0xFF1A1413)
val md_theme_dark_onSurface = Color(0xFFF3E7E2)
val md_theme_dark_surfaceVariant = Color(0xFF554A46)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4B8B4)
val md_theme_dark_outline = Color(0xFF7E7471)
val md_theme_dark_outlineVariant = Color(0xFF554A46)
val md_theme_dark_inverseSurface = Color(0xFFF3E7E2)
val md_theme_dark_inverseOnSurface = Color(0xFF2C2523)
val md_theme_dark_inversePrimary = Color(0xFFA55128)
val md_theme_dark_surfaceContainer = Color(0xFF2C2523)
val md_theme_dark_surfaceContainerHigh = Color(0xFF3D3531)
val md_theme_dark_surfaceContainerHighest = Color(0xFF554A46)
